version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin
      - kubectl version --client
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 325583868777.dkr.ecr.ca-central-1.amazonaws.com
      - REPO_URI=325583868777.dkr.ecr.ca-central-1.amazonaws.com/cicd-dp005
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPO_URI:$IMAGE_TAG .
      - docker tag $REPO_URI:$IMAGE_TAG $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Configuring kubectl...
      - aws eks update-kubeconfig --region ca-central-1 --name EKSDeepDive
      - echo Deploying to EKS...
      - kubectl apply -f deployment.yaml;
      - kubectl apply -f service.yaml;
    